[2022-12-04 05:02:29,598] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-12-04T04:59:12.479146+00:00 [queued]>
[2022-12-04 05:02:29,673] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-12-04T04:59:12.479146+00:00 [queued]>
[2022-12-04 05:02:29,674] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 05:02:29,674] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 05:02:29,674] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 05:02:29,741] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-12-04 04:59:12.479146+00:00
[2022-12-04 05:02:29,748] {standard_task_runner.py:52} INFO - Started process 1603 to run task
[2022-12-04 05:02:29,762] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2022-12-04T04:59:12.479146+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp7pux3zio', '--error-file', '/tmp/tmp9l6dku8v']
[2022-12-04 05:02:29,763] {standard_task_runner.py:77} INFO - Job 196: Subtask download_dataset_task
[2022-12-04 05:02:29,886] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-12-04T04:59:12.479146+00:00 [running]> on host f96e892f1d4c
[2022-12-04 05:02:30,048] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-04T04:59:12.479146+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-04T04:59:12.479146+00:00
[2022-12-04 05:02:30,050] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-04 05:02:30,051] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://datausa.io/api/data?drilldowns=Nation&measures=Population > /opt/***/nation_population.json']
[2022-12-04 05:02:30,124] {subprocess.py:85} INFO - Output:
[2022-12-04 05:02:30,233] {subprocess.py:89} INFO - {"error":"Query must contain at least one measure."}
[2022-12-04 05:02:30,234] {subprocess.py:93} INFO - Command exited with return code 0
[2022-12-04 05:02:30,300] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20221204T045912, start_date=20221204T050229, end_date=20221204T050230
[2022-12-04 05:02:30,402] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 05:02:30,543] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
